# This demonstrates working with branch names

name: Branches

on:
  # When pushing to the relevant folder or to the yml file itself
  push:
    paths:
      - 'branches/**/*'
      - '.github/workflows/branch-test.yml'
  # pull_request:
  #   paths:
  #     - 'branches/**/*'
  #     - '.github/workflows/branch-test.yml'
  #   branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./branches
    steps:
      - name: Setup checkout
        uses: actions/checkout@v2
      - name: Branch information
        id: branchinfo
        run: |
          echo "::set-output name=defaultbranch::"${{ github.event.repository.default_branch }}
          echo "::set-output name=currentbranch::${GITHUB_REF##*/}"
          echo "::set-output name=isdefault::$([[ ${GITHUB_REF##*/} == "${{ github.event.repository.default_branch }}" ]] && echo true || echo false)"
      - name: Current branch name
        run: echo running on branch ${{ steps.branchinfo.outputs.currentbranch }}
      - name: Default branch name
        run: echo default branch is ${{ steps.branchinfo.outputs.defaultbranch }}
      - name: Is default branch?
        run: echo is default ${{ steps.branchinfo.outputs.isdefault }}
      - name: Only do this step on default branch
        if: ${{ steps.branchinfo.outputs.isdefault == 'true' }}
        run: echo "Only executing this step on default branch"
