name: Hello from busybox build and push

on: 
  push:
    paths:
      - 'dockerhub/**/*'
      - '.github/workflows/dockerhub-test.yml'


jobs:
  imagebuild:
    name: Build hello/busybox container image and push if on master branch
    defaults:
      run:
        working-directory: ./dockerhub
    env:
      DOCKERHUB_REPO: curryeleison/hello-action-busybox
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Branch information
        id: branchinfo
        run: |
          echo "::set-output name=defaultbranch::"${{ github.event.repository.default_branch }}
          echo "::set-output name=currentbranch::${GITHUB_REF##*/}"
          echo "::set-output name=isdefault::$([[ ${GITHUB_REF##*/} == "${{ github.event.repository.default_branch }}" ]] && echo true || echo false)"
      - name: Set up QEMU to fetch amd64 and arm64
        id: qemu
        uses: docker/setup-qemu-action@v1
        with:
          platforms: amd64,arm64
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      - name: Docker meta - set up image tags and labels
        id: meta
        uses: docker/metadata-action@v3
        with:
          images: ${{ env.DOCKERHUB_REPO }}
          flavor: |
            latest=${{ steps.branchinfo.outputs.isdefault == 'true' }}
          tags: |
            type=sha
      - name: Login to DockerHub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}
      - name: Debug
        run: | 
          pwd
          ls
      - name: Build and (optionally) push
        uses: docker/build-push-action@v2
        with:
          context: ./dockerhub
          platforms: linux/amd64,linux/arm64
          push: ${{ steps.branchinfo.outputs.isdefault == 'true' }}
          tags: ${{ steps.meta.outputs.tags }}
          labels: ${{ steps.meta.outputs.labels }}
