# This workflow tests the python apps

name: Python testing
  on:
    pull-request: [ $default-branch ]


jobs:
  build:
    runs-on: ubuntu
    steps:
      - actions/checkout@v2
      - name: Set up python
        uses: action/setup-python@v2
        with:
          python-version:3.9
      - name: Install dependencies and set up virtual env
        run: |
          python -m pip install --upgrade pip
          pip install pipenv
          pipenv install --dev
      - name: Check dependencies for security issues
        run: |
          pipenv check
      - name: Linting
        run: |
          pipenv run pylint rational_numbers.py
      - name: Testing
        run: |
          pipenv run pytest
