# This workflow tests the python apps

name: Python testing

on: push
  # push:
  #   paths:
  #     - 'rational-numbers/**/*'
  # pull_request:
  #   branches: [ $default-branch ]

jobs:
  build:
    runs-on: ubuntu
    steps:
      - uses: actions/checkout@v2
      - name: Set up python
        uses: action/setup-python@v2
        with:
          python-version: '3.9'
      - name: Dependencies installation
        run: |
          python -m pip install --upgrade pip
          pip install pipenv pytest
